version: '3.1'
services:
  web:
    image: odoo:15.0
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - ~/local_data:/var/lib/odoo
      - ~/local_data/log:/var/log/odoo
      - ~/local_data/config:/etc/odoo
      - ./beanbakery-addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
      - USER=beanbakery
    secrets:
      - postgresql_password
    networks:
      - my-network
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=beanbakery
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ~/local_data/db:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
    networks:
      - my-network
   
volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  my-network:
    driver: bridge

secrets:
  postgresql_password:
    file: odoo_pg_pass
